Fix extractData to work with non float cols and with params
Archman/beamline pull request #3
Opened 2016-10-07 21:30 UTC by smartsammler

* Add possibility to use extractData for columns with e.g. strings
  instead of floats.
* Use precision used by the SDDS file.
* Add possibility to ask for parameters and not just columns.
* Change ``getAllCols`` to use `sdds`
* Add ``getAllPars`` similar to ``getAllCols``

* *New dependency*: **sdds** (the official sdds Python wrapper)
 * http://www.aps.anl.gov/Accelerator_Systems_Division/Accelerator_Operations_Physics/software.shtml#PythonBinaries
 * http://www.aps.anl.gov/Accelerator_Systems_Division/Accelerator_Operations_Physics/installationGuide_Linux.shtml
  * Unfortunately there is no Package in the PyPI for SDDS at the moment. Furthermore the binaries are for Python 2 only though it is possible to compile the important file for Python 3.

2016-10-10 16:21 UTC, zhangt58 requested changes
@smartsammler Good job! In order to be compatible with the already deployed `beamline` version, it is better to provide the pure python SDDS interface as an extra option, along side the previous external SDDS commands, e.g. the following should be done:
- handle import exceptions when `sdds` cannot be imported, in this case, rollback to the external callback approach;
- Can you make the `sdds` python package, `.whl` or `.egg`? I built it from source code, and could work on my laptop, however some method does not give expected results.

If you including both the pure python and external approaches, I will be glad to merge, thanks!

2016-10-10 16:21 UTC, archman commented on beamline/datautils.py
> +        data = [self.sddsobj.columnData[columns.index(col)][0]
In my laptop, `sddsobj.columnData` just gives a list of `[None]`, `sddsobj.parameterData` works right, so I cannot verify the test script here. Maybe it it the issue of the SDDS python interface.

2016-10-10 16:21 UTC, archman commented on setup.py
> +requiredpackages = ['pyrpn', 'h5py', 'numpy', 'matplotlib', 'pyepics', 'sdds']
Could you please just make `sdds` optional, for the compatibility?

2016-10-19 16:46 UTC, smartsammler commented
Thank you for your input and sorry for the delay.
Should I make a new commit or should I squash/amend the new commit with this PR? (I'm sorry I have no experience with PR reviews so far)

May you test the wheel, before I try to publish it? Unfortunately I needed to zip it to upload it to GitHub
[sddswhl.whl.zip](https://github.com/archman/beamline/files/539658/sddswhl.whl.zip)

2016-10-20 21:19 UTC, archman commented
I've tested with your ``sdds .whl``, ``sddsobj.columnData`` gives right results, that's great!
You can just continue to commit to the PR branch, I think the new commits will automatically show up.
Thank you!

2016-10-31 00:30 UTC, merged